# .streamlit/secrets.toml

OPENAI_API_KEY = "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"

[connections.snowflake]
user = "mram1000"
password = "Surbhi*00"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "txixdpb-qk24061"